
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: 'realtime_searchbox_dev'

  analytics:
    <<: *default
    database: 'realtime_searchbox_analytics'
    migrations_paths: db/analytics_migrate

staging:
  <<: *default
  database: 'realtime_searchbox_staging'

test:
  primary:
    <<: *default
    database: 'realtime_searchbox_test'

  analytics:
    <<: *default
    database: 'realtime_searchbox_analytics_test'
    migrations_paths: db/analytics_migrate


production:
  <primary:
    <<: *default
    database: 'realtime_searchbox_prod'
    url: <%= ENV["DATABASE_URL"] %>

  analytics:
    <<: *default
    database: 'realtime_searchbox_analytics_prod'
    migrations_paths: db/analytics_migrate
    url: <%= ENV["ANALYTICS_DATABASE_URL"] %>
